apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: ofk-no
resources:
  - ../../../base
commonLabels:
  app.kubernetes.io/name: fint-kontroll-user-factory
  app.kubernetes.io/instance: fint-kontroll-user-factory_ofk-no
  app.kubernetes.io/version: latest
  app.kubernetes.io/component: backend
  app.kubernetes.io/part-of: fint-kontroll
  fintlabs.no/team: bas
  fintlabs.no/org-id: ofk.no
patches:
  - patch: |-
      - op: replace
        path: "/spec/orgId"
        value: "ofk.no"
      - op: add
        path: "/spec/resources"
        value:
          limits:
            cpu: "1000m"
            memory: "2000Mi"
          requests:
            cpu: "500m"
            memory: "500Mi"
      - op: replace
        path: "/spec/kafka/acls/0/topic"
        value: "ofk-no.kontroll.*"
      - op: replace
        path: "/spec/kafka/acls/1/topic"
        value: "ofk-no.kontroll.*"
      - op: replace
        path: "/spec/env/3/value"
        value: "ofk-no-fint-kontroll-user-factory"
      - op: replace
        path: "/spec/env/4/value"
        value: "-XX:+ExitOnOutOfMemoryError -Xmx896m -verbose:gc"
      - op: replace
        path: "/spec/env/5/value"
        value: "14"
      - op: replace
        path: "/spec/env/6/value"
        value: "5"
    target:
      kind: Application
      name: fint-kontroll-user-factory















