fint:
  org-id: fintlabs.no
  flyt:
    resource-gateway:
      authorization:
        enable: true
  client:
    base-url: https://beta.felleskomponent.no
  kafka:
    default-replicas: 1
spring:
  kafka:
    bootstrap-servers: localhost:9092
server:
  port: 8088
logging:
  level:
    no.fintlabs.user.UserPublishingComponent: DEBUG